name: to_do_list
version: 1.1.0+2
description: To-Do List App.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  get: 4.6.1
  sqflite: 2.0.2
  cupertino_icons: 1.0.4
  animated_splash_screen: 1.1.0
  flutter_spinkit: 5.1.0
  intl: 0.17.0
  grouped_list: 4.2.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

