name: icheck
version: 1.0.0+1
description: iCheck.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  get: 4.6.5
  sqflite: ^2.2.2
  cupertino_icons: 1.0.5
  animated_splash_screen: ^1.3.0
  flutter_spinkit: 5.1.0
  intl: ^0.18.0
  grouped_list: 5.1.2
  flutter_speed_dial: ^6.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

