name: to_do_list
version: 1.0.0+1
description: To-Do List App.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  get: 4.6.1
  cupertino_icons: 1.0.4
  animated_splash_screen: 1.1.0
  flutter_spinkit: 5.1.0
  google_fonts: 2.2.0
  sqflite: 2.0.1
  intl: 0.17.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

