name: to_do_list
version: 1.0.0+1
description: To-Do List App.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  get: 4.6.1
  sqflite: 2.0.2
  cupertino_icons: 1.0.4
  animated_splash_screen: 1.1.0
  flutter_spinkit: 5.1.0
  google_fonts: 2.2.0
  intl: 0.17.0
  flutter:
    sdk: flutter

dev_dependencies: 
  build_runner: 2.1.7
  hive_generator: 1.1.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

