name: todoey
version: 1.0.0+1
publish_to: none
description: To-Do List App.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  get: 4.6.5
  cupertino_icons: 1.0.5
  sqflite: 2.2.3
  animated_splash_screen: 1.3.0
  flutter_spinkit: 5.1.0
  intl: 0.18.0
  grouped_list: 5.1.2
  flutter_speed_dial: 6.2.0
  flutter: 
    sdk: flutter

dev_dependencies:
  #change_app_package_name: 1.0.0
  #flutter_launcher_name: 0.0.1
  flutter_launcher_icons: 0.9.0
  flutter_lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: "assets/app_icon_round.png"
  android: "app_icon_round"
  ios: true
  remove_alpha_ios: true

flutter_launcher_name:
  name: "Todoey"


flutter: 
  uses-material-design: true
  assets:
    - assets/

